### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by JanBerktold** [markbates/ghi#2]
> go get github.com/markbates/ghi
`    github.com/markbates/ghi/cmd
    ../../../../../go/src/github.com/markbates/ghi/cmd/fetch.go:56: not enough arguments in call to      client.Issues.ListByRepo
    ../../../../../go/src/github.com/markbates/ghi/cmd/fetch.go:69: cannot use issues[i] (type *github.Issue)    as type github.Issue in field value
    ../../../../../go/src/github.com/markbates/ghi/cmd/fetch.go:70: not enough arguments in call to client.Issues.ListComments`

> go version
`   
    go version go1.7.3 darwin/amd64
` 

Might be some issue with outdated dependencies?

**Comment by markbates** [comment]
Looks like github must've changed their client. I haven't had to build this in a long time so I haven't noticed. TBH not sure when I'll get around to upgrading it.
